# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /homes/ah2814/arm11

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /homes/ah2814/arm11

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /homes/ah2814/arm11/CMakeFiles /homes/ah2814/arm11/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /homes/ah2814/arm11/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named assemble

# Build rule for target.
assemble: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 assemble
.PHONY : assemble

# fast build rule for target.
assemble/fast:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/build
.PHONY : assemble/fast

#=============================================================================
# Target rules for targets named compiler

# Build rule for target.
compiler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 compiler
.PHONY : compiler

# fast build rule for target.
compiler/fast:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/build
.PHONY : compiler/fast

#=============================================================================
# Target rules for targets named emulate

# Build rule for target.
emulate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 emulate
.PHONY : emulate

# fast build rule for target.
emulate/fast:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/build
.PHONY : emulate/fast

src/assemble.o: src/assemble.c.o
.PHONY : src/assemble.o

# target to build an object file
src/assemble.c.o:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assemble.c.o
.PHONY : src/assemble.c.o

src/assemble.i: src/assemble.c.i
.PHONY : src/assemble.i

# target to preprocess a source file
src/assemble.c.i:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assemble.c.i
.PHONY : src/assemble.c.i

src/assemble.s: src/assemble.c.s
.PHONY : src/assemble.s

# target to generate assembly for a file
src/assemble.c.s:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assemble.c.s
.PHONY : src/assemble.c.s

src/assembler/assembler.o: src/assembler/assembler.c.o
.PHONY : src/assembler/assembler.o

# target to build an object file
src/assembler/assembler.c.o:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/assembler.c.o
.PHONY : src/assembler/assembler.c.o

src/assembler/assembler.i: src/assembler/assembler.c.i
.PHONY : src/assembler/assembler.i

# target to preprocess a source file
src/assembler/assembler.c.i:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/assembler.c.i
.PHONY : src/assembler/assembler.c.i

src/assembler/assembler.s: src/assembler/assembler.c.s
.PHONY : src/assembler/assembler.s

# target to generate assembly for a file
src/assembler/assembler.c.s:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/assembler.c.s
.PHONY : src/assembler/assembler.c.s

src/assembler/functionTable.o: src/assembler/functionTable.c.o
.PHONY : src/assembler/functionTable.o

# target to build an object file
src/assembler/functionTable.c.o:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/functionTable.c.o
.PHONY : src/assembler/functionTable.c.o

src/assembler/functionTable.i: src/assembler/functionTable.c.i
.PHONY : src/assembler/functionTable.i

# target to preprocess a source file
src/assembler/functionTable.c.i:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/functionTable.c.i
.PHONY : src/assembler/functionTable.c.i

src/assembler/functionTable.s: src/assembler/functionTable.c.s
.PHONY : src/assembler/functionTable.s

# target to generate assembly for a file
src/assembler/functionTable.c.s:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/functionTable.c.s
.PHONY : src/assembler/functionTable.c.s

src/assembler/genInstr.o: src/assembler/genInstr.c.o
.PHONY : src/assembler/genInstr.o

# target to build an object file
src/assembler/genInstr.c.o:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/genInstr.c.o
.PHONY : src/assembler/genInstr.c.o

src/assembler/genInstr.i: src/assembler/genInstr.c.i
.PHONY : src/assembler/genInstr.i

# target to preprocess a source file
src/assembler/genInstr.c.i:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/genInstr.c.i
.PHONY : src/assembler/genInstr.c.i

src/assembler/genInstr.s: src/assembler/genInstr.c.s
.PHONY : src/assembler/genInstr.s

# target to generate assembly for a file
src/assembler/genInstr.c.s:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/genInstr.c.s
.PHONY : src/assembler/genInstr.c.s

src/assembler/io.o: src/assembler/io.c.o
.PHONY : src/assembler/io.o

# target to build an object file
src/assembler/io.c.o:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/io.c.o
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/assembler/io.c.o
.PHONY : src/assembler/io.c.o

src/assembler/io.i: src/assembler/io.c.i
.PHONY : src/assembler/io.i

# target to preprocess a source file
src/assembler/io.c.i:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/io.c.i
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/assembler/io.c.i
.PHONY : src/assembler/io.c.i

src/assembler/io.s: src/assembler/io.c.s
.PHONY : src/assembler/io.s

# target to generate assembly for a file
src/assembler/io.c.s:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/io.c.s
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/assembler/io.c.s
.PHONY : src/assembler/io.c.s

src/assembler/symbolTable.o: src/assembler/symbolTable.c.o
.PHONY : src/assembler/symbolTable.o

# target to build an object file
src/assembler/symbolTable.c.o:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/symbolTable.c.o
.PHONY : src/assembler/symbolTable.c.o

src/assembler/symbolTable.i: src/assembler/symbolTable.c.i
.PHONY : src/assembler/symbolTable.i

# target to preprocess a source file
src/assembler/symbolTable.c.i:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/symbolTable.c.i
.PHONY : src/assembler/symbolTable.c.i

src/assembler/symbolTable.s: src/assembler/symbolTable.c.s
.PHONY : src/assembler/symbolTable.s

# target to generate assembly for a file
src/assembler/symbolTable.c.s:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/symbolTable.c.s
.PHONY : src/assembler/symbolTable.c.s

src/assembler/tokenHandlerUtil.o: src/assembler/tokenHandlerUtil.c.o
.PHONY : src/assembler/tokenHandlerUtil.o

# target to build an object file
src/assembler/tokenHandlerUtil.c.o:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/tokenHandlerUtil.c.o
.PHONY : src/assembler/tokenHandlerUtil.c.o

src/assembler/tokenHandlerUtil.i: src/assembler/tokenHandlerUtil.c.i
.PHONY : src/assembler/tokenHandlerUtil.i

# target to preprocess a source file
src/assembler/tokenHandlerUtil.c.i:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/tokenHandlerUtil.c.i
.PHONY : src/assembler/tokenHandlerUtil.c.i

src/assembler/tokenHandlerUtil.s: src/assembler/tokenHandlerUtil.c.s
.PHONY : src/assembler/tokenHandlerUtil.s

# target to generate assembly for a file
src/assembler/tokenHandlerUtil.c.s:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/tokenHandlerUtil.c.s
.PHONY : src/assembler/tokenHandlerUtil.c.s

src/assembler/tokenHandlers.o: src/assembler/tokenHandlers.c.o
.PHONY : src/assembler/tokenHandlers.o

# target to build an object file
src/assembler/tokenHandlers.c.o:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/tokenHandlers.c.o
.PHONY : src/assembler/tokenHandlers.c.o

src/assembler/tokenHandlers.i: src/assembler/tokenHandlers.c.i
.PHONY : src/assembler/tokenHandlers.i

# target to preprocess a source file
src/assembler/tokenHandlers.c.i:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/tokenHandlers.c.i
.PHONY : src/assembler/tokenHandlers.c.i

src/assembler/tokenHandlers.s: src/assembler/tokenHandlers.c.s
.PHONY : src/assembler/tokenHandlers.s

# target to generate assembly for a file
src/assembler/tokenHandlers.c.s:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/tokenHandlers.c.s
.PHONY : src/assembler/tokenHandlers.c.s

src/assembler/tokenizer.o: src/assembler/tokenizer.c.o
.PHONY : src/assembler/tokenizer.o

# target to build an object file
src/assembler/tokenizer.c.o:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/tokenizer.c.o
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/assembler/tokenizer.c.o
.PHONY : src/assembler/tokenizer.c.o

src/assembler/tokenizer.i: src/assembler/tokenizer.c.i
.PHONY : src/assembler/tokenizer.i

# target to preprocess a source file
src/assembler/tokenizer.c.i:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/tokenizer.c.i
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/assembler/tokenizer.c.i
.PHONY : src/assembler/tokenizer.c.i

src/assembler/tokenizer.s: src/assembler/tokenizer.c.s
.PHONY : src/assembler/tokenizer.s

# target to generate assembly for a file
src/assembler/tokenizer.c.s:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/tokenizer.c.s
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/assembler/tokenizer.c.s
.PHONY : src/assembler/tokenizer.c.s

src/compiler/compiler.o: src/compiler/compiler.c.o
.PHONY : src/compiler/compiler.o

# target to build an object file
src/compiler/compiler.c.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/compiler/compiler.c.o
.PHONY : src/compiler/compiler.c.o

src/compiler/compiler.i: src/compiler/compiler.c.i
.PHONY : src/compiler/compiler.i

# target to preprocess a source file
src/compiler/compiler.c.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/compiler/compiler.c.i
.PHONY : src/compiler/compiler.c.i

src/compiler/compiler.s: src/compiler/compiler.c.s
.PHONY : src/compiler/compiler.s

# target to generate assembly for a file
src/compiler/compiler.c.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/compiler/compiler.c.s
.PHONY : src/compiler/compiler.c.s

src/compiler/compilerFunctionTable.o: src/compiler/compilerFunctionTable.c.o
.PHONY : src/compiler/compilerFunctionTable.o

# target to build an object file
src/compiler/compilerFunctionTable.c.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/compiler/compilerFunctionTable.c.o
.PHONY : src/compiler/compilerFunctionTable.c.o

src/compiler/compilerFunctionTable.i: src/compiler/compilerFunctionTable.c.i
.PHONY : src/compiler/compilerFunctionTable.i

# target to preprocess a source file
src/compiler/compilerFunctionTable.c.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/compiler/compilerFunctionTable.c.i
.PHONY : src/compiler/compilerFunctionTable.c.i

src/compiler/compilerFunctionTable.s: src/compiler/compilerFunctionTable.c.s
.PHONY : src/compiler/compilerFunctionTable.s

# target to generate assembly for a file
src/compiler/compilerFunctionTable.c.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/compiler/compilerFunctionTable.c.s
.PHONY : src/compiler/compilerFunctionTable.c.s

src/compiler/compilerTokenizer.o: src/compiler/compilerTokenizer.c.o
.PHONY : src/compiler/compilerTokenizer.o

# target to build an object file
src/compiler/compilerTokenizer.c.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/compiler/compilerTokenizer.c.o
.PHONY : src/compiler/compilerTokenizer.c.o

src/compiler/compilerTokenizer.i: src/compiler/compilerTokenizer.c.i
.PHONY : src/compiler/compilerTokenizer.i

# target to preprocess a source file
src/compiler/compilerTokenizer.c.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/compiler/compilerTokenizer.c.i
.PHONY : src/compiler/compilerTokenizer.c.i

src/compiler/compilerTokenizer.s: src/compiler/compilerTokenizer.c.s
.PHONY : src/compiler/compilerTokenizer.s

# target to generate assembly for a file
src/compiler/compilerTokenizer.c.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/compiler/compilerTokenizer.c.s
.PHONY : src/compiler/compilerTokenizer.c.s

src/compiler/expressionHandlers.o: src/compiler/expressionHandlers.c.o
.PHONY : src/compiler/expressionHandlers.o

# target to build an object file
src/compiler/expressionHandlers.c.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/compiler/expressionHandlers.c.o
.PHONY : src/compiler/expressionHandlers.c.o

src/compiler/expressionHandlers.i: src/compiler/expressionHandlers.c.i
.PHONY : src/compiler/expressionHandlers.i

# target to preprocess a source file
src/compiler/expressionHandlers.c.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/compiler/expressionHandlers.c.i
.PHONY : src/compiler/expressionHandlers.c.i

src/compiler/expressionHandlers.s: src/compiler/expressionHandlers.c.s
.PHONY : src/compiler/expressionHandlers.s

# target to generate assembly for a file
src/compiler/expressionHandlers.c.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/compiler/expressionHandlers.c.s
.PHONY : src/compiler/expressionHandlers.c.s

src/compiler/instructionMaker.o: src/compiler/instructionMaker.c.o
.PHONY : src/compiler/instructionMaker.o

# target to build an object file
src/compiler/instructionMaker.c.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/compiler/instructionMaker.c.o
.PHONY : src/compiler/instructionMaker.c.o

src/compiler/instructionMaker.i: src/compiler/instructionMaker.c.i
.PHONY : src/compiler/instructionMaker.i

# target to preprocess a source file
src/compiler/instructionMaker.c.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/compiler/instructionMaker.c.i
.PHONY : src/compiler/instructionMaker.c.i

src/compiler/instructionMaker.s: src/compiler/instructionMaker.c.s
.PHONY : src/compiler/instructionMaker.s

# target to generate assembly for a file
src/compiler/instructionMaker.c.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/compiler/instructionMaker.c.s
.PHONY : src/compiler/instructionMaker.c.s

src/compiler/variable.o: src/compiler/variable.c.o
.PHONY : src/compiler/variable.o

# target to build an object file
src/compiler/variable.c.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/compiler/variable.c.o
.PHONY : src/compiler/variable.c.o

src/compiler/variable.i: src/compiler/variable.c.i
.PHONY : src/compiler/variable.i

# target to preprocess a source file
src/compiler/variable.c.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/compiler/variable.c.i
.PHONY : src/compiler/variable.c.i

src/compiler/variable.s: src/compiler/variable.c.s
.PHONY : src/compiler/variable.s

# target to generate assembly for a file
src/compiler/variable.c.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/compiler/variable.c.s
.PHONY : src/compiler/variable.c.s

src/compilerMain.o: src/compilerMain.c.o
.PHONY : src/compilerMain.o

# target to build an object file
src/compilerMain.c.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/compilerMain.c.o
.PHONY : src/compilerMain.c.o

src/compilerMain.i: src/compilerMain.c.i
.PHONY : src/compilerMain.i

# target to preprocess a source file
src/compilerMain.c.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/compilerMain.c.i
.PHONY : src/compilerMain.c.i

src/compilerMain.s: src/compilerMain.c.s
.PHONY : src/compilerMain.s

# target to generate assembly for a file
src/compilerMain.c.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/compilerMain.c.s
.PHONY : src/compilerMain.c.s

src/emulate.o: src/emulate.c.o
.PHONY : src/emulate.o

# target to build an object file
src/emulate.c.o:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulate.c.o
.PHONY : src/emulate.c.o

src/emulate.i: src/emulate.c.i
.PHONY : src/emulate.i

# target to preprocess a source file
src/emulate.c.i:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulate.c.i
.PHONY : src/emulate.c.i

src/emulate.s: src/emulate.c.s
.PHONY : src/emulate.s

# target to generate assembly for a file
src/emulate.c.s:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulate.c.s
.PHONY : src/emulate.c.s

src/emulator/branch.o: src/emulator/branch.c.o
.PHONY : src/emulator/branch.o

# target to build an object file
src/emulator/branch.c.o:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/branch.c.o
.PHONY : src/emulator/branch.c.o

src/emulator/branch.i: src/emulator/branch.c.i
.PHONY : src/emulator/branch.i

# target to preprocess a source file
src/emulator/branch.c.i:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/branch.c.i
.PHONY : src/emulator/branch.c.i

src/emulator/branch.s: src/emulator/branch.c.s
.PHONY : src/emulator/branch.s

# target to generate assembly for a file
src/emulator/branch.c.s:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/branch.c.s
.PHONY : src/emulator/branch.c.s

src/emulator/checkCond.o: src/emulator/checkCond.c.o
.PHONY : src/emulator/checkCond.o

# target to build an object file
src/emulator/checkCond.c.o:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/checkCond.c.o
.PHONY : src/emulator/checkCond.c.o

src/emulator/checkCond.i: src/emulator/checkCond.c.i
.PHONY : src/emulator/checkCond.i

# target to preprocess a source file
src/emulator/checkCond.c.i:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/checkCond.c.i
.PHONY : src/emulator/checkCond.c.i

src/emulator/checkCond.s: src/emulator/checkCond.c.s
.PHONY : src/emulator/checkCond.s

# target to generate assembly for a file
src/emulator/checkCond.c.s:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/checkCond.c.s
.PHONY : src/emulator/checkCond.c.s

src/emulator/dataProcess.o: src/emulator/dataProcess.c.o
.PHONY : src/emulator/dataProcess.o

# target to build an object file
src/emulator/dataProcess.c.o:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/dataProcess.c.o
.PHONY : src/emulator/dataProcess.c.o

src/emulator/dataProcess.i: src/emulator/dataProcess.c.i
.PHONY : src/emulator/dataProcess.i

# target to preprocess a source file
src/emulator/dataProcess.c.i:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/dataProcess.c.i
.PHONY : src/emulator/dataProcess.c.i

src/emulator/dataProcess.s: src/emulator/dataProcess.c.s
.PHONY : src/emulator/dataProcess.s

# target to generate assembly for a file
src/emulator/dataProcess.c.s:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/dataProcess.c.s
.PHONY : src/emulator/dataProcess.c.s

src/emulator/dataTransfer.o: src/emulator/dataTransfer.c.o
.PHONY : src/emulator/dataTransfer.o

# target to build an object file
src/emulator/dataTransfer.c.o:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/dataTransfer.c.o
.PHONY : src/emulator/dataTransfer.c.o

src/emulator/dataTransfer.i: src/emulator/dataTransfer.c.i
.PHONY : src/emulator/dataTransfer.i

# target to preprocess a source file
src/emulator/dataTransfer.c.i:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/dataTransfer.c.i
.PHONY : src/emulator/dataTransfer.c.i

src/emulator/dataTransfer.s: src/emulator/dataTransfer.c.s
.PHONY : src/emulator/dataTransfer.s

# target to generate assembly for a file
src/emulator/dataTransfer.c.s:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/dataTransfer.c.s
.PHONY : src/emulator/dataTransfer.c.s

src/emulator/decodeAndExecute.o: src/emulator/decodeAndExecute.c.o
.PHONY : src/emulator/decodeAndExecute.o

# target to build an object file
src/emulator/decodeAndExecute.c.o:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/decodeAndExecute.c.o
.PHONY : src/emulator/decodeAndExecute.c.o

src/emulator/decodeAndExecute.i: src/emulator/decodeAndExecute.c.i
.PHONY : src/emulator/decodeAndExecute.i

# target to preprocess a source file
src/emulator/decodeAndExecute.c.i:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/decodeAndExecute.c.i
.PHONY : src/emulator/decodeAndExecute.c.i

src/emulator/decodeAndExecute.s: src/emulator/decodeAndExecute.c.s
.PHONY : src/emulator/decodeAndExecute.s

# target to generate assembly for a file
src/emulator/decodeAndExecute.c.s:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/decodeAndExecute.c.s
.PHONY : src/emulator/decodeAndExecute.c.s

src/emulator/getOperand2.o: src/emulator/getOperand2.c.o
.PHONY : src/emulator/getOperand2.o

# target to build an object file
src/emulator/getOperand2.c.o:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/getOperand2.c.o
.PHONY : src/emulator/getOperand2.c.o

src/emulator/getOperand2.i: src/emulator/getOperand2.c.i
.PHONY : src/emulator/getOperand2.i

# target to preprocess a source file
src/emulator/getOperand2.c.i:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/getOperand2.c.i
.PHONY : src/emulator/getOperand2.c.i

src/emulator/getOperand2.s: src/emulator/getOperand2.c.s
.PHONY : src/emulator/getOperand2.s

# target to generate assembly for a file
src/emulator/getOperand2.c.s:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/getOperand2.c.s
.PHONY : src/emulator/getOperand2.c.s

src/emulator/global_state.o: src/emulator/global_state.c.o
.PHONY : src/emulator/global_state.o

# target to build an object file
src/emulator/global_state.c.o:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/global_state.c.o
.PHONY : src/emulator/global_state.c.o

src/emulator/global_state.i: src/emulator/global_state.c.i
.PHONY : src/emulator/global_state.i

# target to preprocess a source file
src/emulator/global_state.c.i:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/global_state.c.i
.PHONY : src/emulator/global_state.c.i

src/emulator/global_state.s: src/emulator/global_state.c.s
.PHONY : src/emulator/global_state.s

# target to generate assembly for a file
src/emulator/global_state.c.s:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/global_state.c.s
.PHONY : src/emulator/global_state.c.s

src/emulator/iMultiply.o: src/emulator/iMultiply.c.o
.PHONY : src/emulator/iMultiply.o

# target to build an object file
src/emulator/iMultiply.c.o:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/iMultiply.c.o
.PHONY : src/emulator/iMultiply.c.o

src/emulator/iMultiply.i: src/emulator/iMultiply.c.i
.PHONY : src/emulator/iMultiply.i

# target to preprocess a source file
src/emulator/iMultiply.c.i:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/iMultiply.c.i
.PHONY : src/emulator/iMultiply.c.i

src/emulator/iMultiply.s: src/emulator/iMultiply.c.s
.PHONY : src/emulator/iMultiply.s

# target to generate assembly for a file
src/emulator/iMultiply.c.s:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/iMultiply.c.s
.PHONY : src/emulator/iMultiply.c.s

src/emulator/printState.o: src/emulator/printState.c.o
.PHONY : src/emulator/printState.o

# target to build an object file
src/emulator/printState.c.o:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/printState.c.o
.PHONY : src/emulator/printState.c.o

src/emulator/printState.i: src/emulator/printState.c.i
.PHONY : src/emulator/printState.i

# target to preprocess a source file
src/emulator/printState.c.i:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/printState.c.i
.PHONY : src/emulator/printState.c.i

src/emulator/printState.s: src/emulator/printState.c.s
.PHONY : src/emulator/printState.s

# target to generate assembly for a file
src/emulator/printState.c.s:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/printState.c.s
.PHONY : src/emulator/printState.c.s

src/emulator/updateCPSR.o: src/emulator/updateCPSR.c.o
.PHONY : src/emulator/updateCPSR.o

# target to build an object file
src/emulator/updateCPSR.c.o:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/updateCPSR.c.o
.PHONY : src/emulator/updateCPSR.c.o

src/emulator/updateCPSR.i: src/emulator/updateCPSR.c.i
.PHONY : src/emulator/updateCPSR.i

# target to preprocess a source file
src/emulator/updateCPSR.c.i:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/updateCPSR.c.i
.PHONY : src/emulator/updateCPSR.c.i

src/emulator/updateCPSR.s: src/emulator/updateCPSR.c.s
.PHONY : src/emulator/updateCPSR.s

# target to generate assembly for a file
src/emulator/updateCPSR.c.s:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/updateCPSR.c.s
.PHONY : src/emulator/updateCPSR.c.s

src/util/ListMap.o: src/util/ListMap.c.o
.PHONY : src/util/ListMap.o

# target to build an object file
src/util/ListMap.c.o:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/util/ListMap.c.o
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/util/ListMap.c.o
.PHONY : src/util/ListMap.c.o

src/util/ListMap.i: src/util/ListMap.c.i
.PHONY : src/util/ListMap.i

# target to preprocess a source file
src/util/ListMap.c.i:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/util/ListMap.c.i
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/util/ListMap.c.i
.PHONY : src/util/ListMap.c.i

src/util/ListMap.s: src/util/ListMap.c.s
.PHONY : src/util/ListMap.s

# target to generate assembly for a file
src/util/ListMap.c.s:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/util/ListMap.c.s
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/util/ListMap.c.s
.PHONY : src/util/ListMap.c.s

src/util/ListMapIterator.o: src/util/ListMapIterator.c.o
.PHONY : src/util/ListMapIterator.o

# target to build an object file
src/util/ListMapIterator.c.o:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/util/ListMapIterator.c.o
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/util/ListMapIterator.c.o
.PHONY : src/util/ListMapIterator.c.o

src/util/ListMapIterator.i: src/util/ListMapIterator.c.i
.PHONY : src/util/ListMapIterator.i

# target to preprocess a source file
src/util/ListMapIterator.c.i:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/util/ListMapIterator.c.i
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/util/ListMapIterator.c.i
.PHONY : src/util/ListMapIterator.c.i

src/util/ListMapIterator.s: src/util/ListMapIterator.c.s
.PHONY : src/util/ListMapIterator.s

# target to generate assembly for a file
src/util/ListMapIterator.c.s:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/util/ListMapIterator.c.s
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/util/ListMapIterator.c.s
.PHONY : src/util/ListMapIterator.c.s

src/util/ListMapNode.o: src/util/ListMapNode.c.o
.PHONY : src/util/ListMapNode.o

# target to build an object file
src/util/ListMapNode.c.o:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/util/ListMapNode.c.o
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/util/ListMapNode.c.o
.PHONY : src/util/ListMapNode.c.o

src/util/ListMapNode.i: src/util/ListMapNode.c.i
.PHONY : src/util/ListMapNode.i

# target to preprocess a source file
src/util/ListMapNode.c.i:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/util/ListMapNode.c.i
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/util/ListMapNode.c.i
.PHONY : src/util/ListMapNode.c.i

src/util/ListMapNode.s: src/util/ListMapNode.c.s
.PHONY : src/util/ListMapNode.s

# target to generate assembly for a file
src/util/ListMapNode.c.s:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/util/ListMapNode.c.s
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/util/ListMapNode.c.s
.PHONY : src/util/ListMapNode.c.s

src/util/util.o: src/util/util.c.o
.PHONY : src/util/util.o

# target to build an object file
src/util/util.c.o:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/util/util.c.o
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/util/util.c.o
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/util/util.c.o
.PHONY : src/util/util.c.o

src/util/util.i: src/util/util.c.i
.PHONY : src/util/util.i

# target to preprocess a source file
src/util/util.c.i:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/util/util.c.i
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/util/util.c.i
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/util/util.c.i
.PHONY : src/util/util.c.i

src/util/util.s: src/util/util.c.s
.PHONY : src/util/util.s

# target to generate assembly for a file
src/util/util.c.s:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/util/util.c.s
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/util/util.c.s
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/util/util.c.s
.PHONY : src/util/util.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... assemble"
	@echo "... compiler"
	@echo "... edit_cache"
	@echo "... emulate"
	@echo "... rebuild_cache"
	@echo "... src/assemble.o"
	@echo "... src/assemble.i"
	@echo "... src/assemble.s"
	@echo "... src/assembler/assembler.o"
	@echo "... src/assembler/assembler.i"
	@echo "... src/assembler/assembler.s"
	@echo "... src/assembler/functionTable.o"
	@echo "... src/assembler/functionTable.i"
	@echo "... src/assembler/functionTable.s"
	@echo "... src/assembler/genInstr.o"
	@echo "... src/assembler/genInstr.i"
	@echo "... src/assembler/genInstr.s"
	@echo "... src/assembler/io.o"
	@echo "... src/assembler/io.i"
	@echo "... src/assembler/io.s"
	@echo "... src/assembler/symbolTable.o"
	@echo "... src/assembler/symbolTable.i"
	@echo "... src/assembler/symbolTable.s"
	@echo "... src/assembler/tokenHandlerUtil.o"
	@echo "... src/assembler/tokenHandlerUtil.i"
	@echo "... src/assembler/tokenHandlerUtil.s"
	@echo "... src/assembler/tokenHandlers.o"
	@echo "... src/assembler/tokenHandlers.i"
	@echo "... src/assembler/tokenHandlers.s"
	@echo "... src/assembler/tokenizer.o"
	@echo "... src/assembler/tokenizer.i"
	@echo "... src/assembler/tokenizer.s"
	@echo "... src/compiler/compiler.o"
	@echo "... src/compiler/compiler.i"
	@echo "... src/compiler/compiler.s"
	@echo "... src/compiler/compilerFunctionTable.o"
	@echo "... src/compiler/compilerFunctionTable.i"
	@echo "... src/compiler/compilerFunctionTable.s"
	@echo "... src/compiler/compilerTokenizer.o"
	@echo "... src/compiler/compilerTokenizer.i"
	@echo "... src/compiler/compilerTokenizer.s"
	@echo "... src/compiler/expressionHandlers.o"
	@echo "... src/compiler/expressionHandlers.i"
	@echo "... src/compiler/expressionHandlers.s"
	@echo "... src/compiler/instructionMaker.o"
	@echo "... src/compiler/instructionMaker.i"
	@echo "... src/compiler/instructionMaker.s"
	@echo "... src/compiler/variable.o"
	@echo "... src/compiler/variable.i"
	@echo "... src/compiler/variable.s"
	@echo "... src/compilerMain.o"
	@echo "... src/compilerMain.i"
	@echo "... src/compilerMain.s"
	@echo "... src/emulate.o"
	@echo "... src/emulate.i"
	@echo "... src/emulate.s"
	@echo "... src/emulator/branch.o"
	@echo "... src/emulator/branch.i"
	@echo "... src/emulator/branch.s"
	@echo "... src/emulator/checkCond.o"
	@echo "... src/emulator/checkCond.i"
	@echo "... src/emulator/checkCond.s"
	@echo "... src/emulator/dataProcess.o"
	@echo "... src/emulator/dataProcess.i"
	@echo "... src/emulator/dataProcess.s"
	@echo "... src/emulator/dataTransfer.o"
	@echo "... src/emulator/dataTransfer.i"
	@echo "... src/emulator/dataTransfer.s"
	@echo "... src/emulator/decodeAndExecute.o"
	@echo "... src/emulator/decodeAndExecute.i"
	@echo "... src/emulator/decodeAndExecute.s"
	@echo "... src/emulator/getOperand2.o"
	@echo "... src/emulator/getOperand2.i"
	@echo "... src/emulator/getOperand2.s"
	@echo "... src/emulator/global_state.o"
	@echo "... src/emulator/global_state.i"
	@echo "... src/emulator/global_state.s"
	@echo "... src/emulator/iMultiply.o"
	@echo "... src/emulator/iMultiply.i"
	@echo "... src/emulator/iMultiply.s"
	@echo "... src/emulator/printState.o"
	@echo "... src/emulator/printState.i"
	@echo "... src/emulator/printState.s"
	@echo "... src/emulator/updateCPSR.o"
	@echo "... src/emulator/updateCPSR.i"
	@echo "... src/emulator/updateCPSR.s"
	@echo "... src/util/ListMap.o"
	@echo "... src/util/ListMap.i"
	@echo "... src/util/ListMap.s"
	@echo "... src/util/ListMapIterator.o"
	@echo "... src/util/ListMapIterator.i"
	@echo "... src/util/ListMapIterator.s"
	@echo "... src/util/ListMapNode.o"
	@echo "... src/util/ListMapNode.i"
	@echo "... src/util/ListMapNode.s"
	@echo "... src/util/util.o"
	@echo "... src/util/util.i"
	@echo "... src/util/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

