# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /homes/ah2814/assembler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /homes/ah2814/assembler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /homes/ah2814/assembler/CMakeFiles /homes/ah2814/assembler/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /homes/ah2814/assembler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named assemble

# Build rule for target.
assemble: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 assemble
.PHONY : assemble

# fast build rule for target.
assemble/fast:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/build
.PHONY : assemble/fast

#=============================================================================
# Target rules for targets named emulate

# Build rule for target.
emulate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 emulate
.PHONY : emulate

# fast build rule for target.
emulate/fast:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/build
.PHONY : emulate/fast

# target to build an object file
src/assemble.o:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assemble.o
.PHONY : src/assemble.o

# target to preprocess a source file
src/assemble.i:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assemble.i
.PHONY : src/assemble.i

# target to generate assembly for a file
src/assemble.s:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assemble.s
.PHONY : src/assemble.s

# target to build an object file
src/assembler/assembler.o:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/assembler.o
.PHONY : src/assembler/assembler.o

# target to preprocess a source file
src/assembler/assembler.i:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/assembler.i
.PHONY : src/assembler/assembler.i

# target to generate assembly for a file
src/assembler/assembler.s:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/assembler.s
.PHONY : src/assembler/assembler.s

# target to build an object file
src/assembler/functionTable.o:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/functionTable.o
.PHONY : src/assembler/functionTable.o

# target to preprocess a source file
src/assembler/functionTable.i:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/functionTable.i
.PHONY : src/assembler/functionTable.i

# target to generate assembly for a file
src/assembler/functionTable.s:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/functionTable.s
.PHONY : src/assembler/functionTable.s

# target to build an object file
src/assembler/genInstr.o:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/genInstr.o
.PHONY : src/assembler/genInstr.o

# target to preprocess a source file
src/assembler/genInstr.i:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/genInstr.i
.PHONY : src/assembler/genInstr.i

# target to generate assembly for a file
src/assembler/genInstr.s:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/genInstr.s
.PHONY : src/assembler/genInstr.s

# target to build an object file
src/assembler/io.o:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/io.o
.PHONY : src/assembler/io.o

# target to preprocess a source file
src/assembler/io.i:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/io.i
.PHONY : src/assembler/io.i

# target to generate assembly for a file
src/assembler/io.s:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/io.s
.PHONY : src/assembler/io.s

# target to build an object file
src/assembler/symbolTable.o:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/symbolTable.o
.PHONY : src/assembler/symbolTable.o

# target to preprocess a source file
src/assembler/symbolTable.i:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/symbolTable.i
.PHONY : src/assembler/symbolTable.i

# target to generate assembly for a file
src/assembler/symbolTable.s:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/symbolTable.s
.PHONY : src/assembler/symbolTable.s

# target to build an object file
src/assembler/tokenHandlers.o:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/tokenHandlers.o
.PHONY : src/assembler/tokenHandlers.o

# target to preprocess a source file
src/assembler/tokenHandlers.i:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/tokenHandlers.i
.PHONY : src/assembler/tokenHandlers.i

# target to generate assembly for a file
src/assembler/tokenHandlers.s:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/tokenHandlers.s
.PHONY : src/assembler/tokenHandlers.s

# target to build an object file
src/assembler/tokenizer.o:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/tokenizer.o
.PHONY : src/assembler/tokenizer.o

# target to preprocess a source file
src/assembler/tokenizer.i:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/tokenizer.i
.PHONY : src/assembler/tokenizer.i

# target to generate assembly for a file
src/assembler/tokenizer.s:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/assembler/tokenizer.s
.PHONY : src/assembler/tokenizer.s

# target to build an object file
src/emulate.o:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulate.o
.PHONY : src/emulate.o

# target to preprocess a source file
src/emulate.i:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulate.i
.PHONY : src/emulate.i

# target to generate assembly for a file
src/emulate.s:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulate.s
.PHONY : src/emulate.s

# target to build an object file
src/emulator/branch.o:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/branch.o
.PHONY : src/emulator/branch.o

# target to preprocess a source file
src/emulator/branch.i:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/branch.i
.PHONY : src/emulator/branch.i

# target to generate assembly for a file
src/emulator/branch.s:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/branch.s
.PHONY : src/emulator/branch.s

# target to build an object file
src/emulator/checkCond.o:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/checkCond.o
.PHONY : src/emulator/checkCond.o

# target to preprocess a source file
src/emulator/checkCond.i:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/checkCond.i
.PHONY : src/emulator/checkCond.i

# target to generate assembly for a file
src/emulator/checkCond.s:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/checkCond.s
.PHONY : src/emulator/checkCond.s

# target to build an object file
src/emulator/dataProcess.o:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/dataProcess.o
.PHONY : src/emulator/dataProcess.o

# target to preprocess a source file
src/emulator/dataProcess.i:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/dataProcess.i
.PHONY : src/emulator/dataProcess.i

# target to generate assembly for a file
src/emulator/dataProcess.s:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/dataProcess.s
.PHONY : src/emulator/dataProcess.s

# target to build an object file
src/emulator/dataTransfer.o:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/dataTransfer.o
.PHONY : src/emulator/dataTransfer.o

# target to preprocess a source file
src/emulator/dataTransfer.i:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/dataTransfer.i
.PHONY : src/emulator/dataTransfer.i

# target to generate assembly for a file
src/emulator/dataTransfer.s:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/dataTransfer.s
.PHONY : src/emulator/dataTransfer.s

# target to build an object file
src/emulator/decodeAndExecute.o:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/decodeAndExecute.o
.PHONY : src/emulator/decodeAndExecute.o

# target to preprocess a source file
src/emulator/decodeAndExecute.i:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/decodeAndExecute.i
.PHONY : src/emulator/decodeAndExecute.i

# target to generate assembly for a file
src/emulator/decodeAndExecute.s:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/decodeAndExecute.s
.PHONY : src/emulator/decodeAndExecute.s

# target to build an object file
src/emulator/getOperand2.o:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/getOperand2.o
.PHONY : src/emulator/getOperand2.o

# target to preprocess a source file
src/emulator/getOperand2.i:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/getOperand2.i
.PHONY : src/emulator/getOperand2.i

# target to generate assembly for a file
src/emulator/getOperand2.s:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/getOperand2.s
.PHONY : src/emulator/getOperand2.s

# target to build an object file
src/emulator/global_state.o:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/global_state.o
.PHONY : src/emulator/global_state.o

# target to preprocess a source file
src/emulator/global_state.i:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/global_state.i
.PHONY : src/emulator/global_state.i

# target to generate assembly for a file
src/emulator/global_state.s:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/global_state.s
.PHONY : src/emulator/global_state.s

# target to build an object file
src/emulator/iMultiply.o:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/iMultiply.o
.PHONY : src/emulator/iMultiply.o

# target to preprocess a source file
src/emulator/iMultiply.i:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/iMultiply.i
.PHONY : src/emulator/iMultiply.i

# target to generate assembly for a file
src/emulator/iMultiply.s:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/iMultiply.s
.PHONY : src/emulator/iMultiply.s

# target to build an object file
src/emulator/printState.o:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/printState.o
.PHONY : src/emulator/printState.o

# target to preprocess a source file
src/emulator/printState.i:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/printState.i
.PHONY : src/emulator/printState.i

# target to generate assembly for a file
src/emulator/printState.s:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/printState.s
.PHONY : src/emulator/printState.s

# target to build an object file
src/emulator/updateCPSR.o:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/updateCPSR.o
.PHONY : src/emulator/updateCPSR.o

# target to preprocess a source file
src/emulator/updateCPSR.i:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/updateCPSR.i
.PHONY : src/emulator/updateCPSR.i

# target to generate assembly for a file
src/emulator/updateCPSR.s:
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/emulator/updateCPSR.s
.PHONY : src/emulator/updateCPSR.s

# target to build an object file
src/util/ListMap.o:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/util/ListMap.o
.PHONY : src/util/ListMap.o

# target to preprocess a source file
src/util/ListMap.i:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/util/ListMap.i
.PHONY : src/util/ListMap.i

# target to generate assembly for a file
src/util/ListMap.s:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/util/ListMap.s
.PHONY : src/util/ListMap.s

# target to build an object file
src/util/ListMapIterator.o:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/util/ListMapIterator.o
.PHONY : src/util/ListMapIterator.o

# target to preprocess a source file
src/util/ListMapIterator.i:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/util/ListMapIterator.i
.PHONY : src/util/ListMapIterator.i

# target to generate assembly for a file
src/util/ListMapIterator.s:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/util/ListMapIterator.s
.PHONY : src/util/ListMapIterator.s

# target to build an object file
src/util/ListMapNode.o:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/util/ListMapNode.o
.PHONY : src/util/ListMapNode.o

# target to preprocess a source file
src/util/ListMapNode.i:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/util/ListMapNode.i
.PHONY : src/util/ListMapNode.i

# target to generate assembly for a file
src/util/ListMapNode.s:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/util/ListMapNode.s
.PHONY : src/util/ListMapNode.s

# target to build an object file
src/util/util.o:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/util/util.o
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/util/util.o
.PHONY : src/util/util.o

# target to preprocess a source file
src/util/util.i:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/util/util.i
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/util/util.i
.PHONY : src/util/util.i

# target to generate assembly for a file
src/util/util.s:
	$(MAKE) -f CMakeFiles/assemble.dir/build.make CMakeFiles/assemble.dir/src/util/util.s
	$(MAKE) -f CMakeFiles/emulate.dir/build.make CMakeFiles/emulate.dir/src/util/util.s
.PHONY : src/util/util.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... assemble"
	@echo "... edit_cache"
	@echo "... emulate"
	@echo "... rebuild_cache"
	@echo "... src/assemble.o"
	@echo "... src/assemble.i"
	@echo "... src/assemble.s"
	@echo "... src/assembler/assembler.o"
	@echo "... src/assembler/assembler.i"
	@echo "... src/assembler/assembler.s"
	@echo "... src/assembler/functionTable.o"
	@echo "... src/assembler/functionTable.i"
	@echo "... src/assembler/functionTable.s"
	@echo "... src/assembler/genInstr.o"
	@echo "... src/assembler/genInstr.i"
	@echo "... src/assembler/genInstr.s"
	@echo "... src/assembler/io.o"
	@echo "... src/assembler/io.i"
	@echo "... src/assembler/io.s"
	@echo "... src/assembler/symbolTable.o"
	@echo "... src/assembler/symbolTable.i"
	@echo "... src/assembler/symbolTable.s"
	@echo "... src/assembler/tokenHandlers.o"
	@echo "... src/assembler/tokenHandlers.i"
	@echo "... src/assembler/tokenHandlers.s"
	@echo "... src/assembler/tokenizer.o"
	@echo "... src/assembler/tokenizer.i"
	@echo "... src/assembler/tokenizer.s"
	@echo "... src/emulate.o"
	@echo "... src/emulate.i"
	@echo "... src/emulate.s"
	@echo "... src/emulator/branch.o"
	@echo "... src/emulator/branch.i"
	@echo "... src/emulator/branch.s"
	@echo "... src/emulator/checkCond.o"
	@echo "... src/emulator/checkCond.i"
	@echo "... src/emulator/checkCond.s"
	@echo "... src/emulator/dataProcess.o"
	@echo "... src/emulator/dataProcess.i"
	@echo "... src/emulator/dataProcess.s"
	@echo "... src/emulator/dataTransfer.o"
	@echo "... src/emulator/dataTransfer.i"
	@echo "... src/emulator/dataTransfer.s"
	@echo "... src/emulator/decodeAndExecute.o"
	@echo "... src/emulator/decodeAndExecute.i"
	@echo "... src/emulator/decodeAndExecute.s"
	@echo "... src/emulator/getOperand2.o"
	@echo "... src/emulator/getOperand2.i"
	@echo "... src/emulator/getOperand2.s"
	@echo "... src/emulator/global_state.o"
	@echo "... src/emulator/global_state.i"
	@echo "... src/emulator/global_state.s"
	@echo "... src/emulator/iMultiply.o"
	@echo "... src/emulator/iMultiply.i"
	@echo "... src/emulator/iMultiply.s"
	@echo "... src/emulator/printState.o"
	@echo "... src/emulator/printState.i"
	@echo "... src/emulator/printState.s"
	@echo "... src/emulator/updateCPSR.o"
	@echo "... src/emulator/updateCPSR.i"
	@echo "... src/emulator/updateCPSR.s"
	@echo "... src/util/ListMap.o"
	@echo "... src/util/ListMap.i"
	@echo "... src/util/ListMap.s"
	@echo "... src/util/ListMapIterator.o"
	@echo "... src/util/ListMapIterator.i"
	@echo "... src/util/ListMapIterator.s"
	@echo "... src/util/ListMapNode.o"
	@echo "... src/util/ListMapNode.i"
	@echo "... src/util/ListMapNode.s"
	@echo "... src/util/util.o"
	@echo "... src/util/util.i"
	@echo "... src/util/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

